/**
 * Templates written by `crew init`. These are commented YAML files whose
 * shape mirrors docs/06-config-reference.yaml and examples/safety-policy-example.yaml.
 * They parse cleanly through the zod schemas (verified by tests).
 */

export interface InitTemplateOptions {
  factoryName: string;
  timezone?: string;
  /**
   * Absolute path to the Dispatch sqlite db. When omitted the template falls
   * back to the relative default — but `crew init` always passes the
   * absolute `<factory_root>/dispatch.sqlite` so the generated config points at
   * the SAME db the orchestrator + dashboard use, independent of cwd.
   */
  sqlitePath?: string;
}

export function defaultConfigYaml(opts: InitTemplateOptions): string {
  const timezone = opts.timezone ?? "Europe/London";
  const sqlitePath = opts.sqlitePath ?? "./.dispatch/dispatch.sqlite";
  return `# Crew factory configuration.
# Generated by 'crew init'. Edit to match your repos and agents.

factory:
  name: ${opts.factoryName}
  mode: local_strict # local_loose | local_strict | shared_team
  timezone: ${timezone}

dispatch:
  mode: local # local | shared
  local:
    sqlite_path: ${sqlitePath}
  default_policy_pack: solo_loose

memory:
  enabled: true
  mode: local
  # Real Memory MCP server. Leave command null to use the offline Null client.
  # When enabled + command set, lore is pre-fetched (async) before the sync
  # packet build and suggestions are flushed (async) afterwards.
  mcp:
    command: null # e.g. "npx" or "memory-mcp"
    args: [] # e.g. ["-y", "memory-mcp", "serve", "--stdio"]
  # Memory CLI write bridge (preferred for the onboard flush). When set — or when
  # MEMORY_CLI_BIN is in the environment — onboarding writes the repo digest +
  # feature inventory via the memory CLI verbs (digest set / feature add) into the
  # sqlite named by MEMORY_DB, the SAME store the dashboard's Memory views read.
  # No MCP server is spawned. Env (MEMORY_CLI_BIN) wins over this value.
  cli:
    command: null # e.g. "/path/to/memory/dist/bin/memory.js"; or set MEMORY_CLI_BIN
  required_before:
    tags:
      - auth
      - payments
      - migrations
      - public_api
      - security
  suggestion_policy:
    after_ticket_done: true
    auto_approve: false # never auto-approve durable knowledge

# Register your repositories here. 'crew scan' can detect branch + stack.
repos: []
# - id: auth-service
#   name: auth-service
#   path: ./repos/auth-service
#   default_branch: main
#   protected_branches: [main, release/*]
#   stack: python
#   package_manager: poetry
#   test_command: poetry run pytest
#   lint_command: poetry run ruff check .
#   typecheck_command: poetry run mypy auth_service
#   coverage_command: poetry run pytest --cov=auth_service
#   mutation_mode: branch_only
#   risk_level: high
#   # Per-repo Definition-of-Done override (I3). Omit to inherit the factory
#   # default below. A gate with no matching command is SKIPPED, not failed.
#   definition_of_done:
#     enabled: true   # set false (or run with GAFFER_DOD=0) to disable enforcement
#     tests: true
#     typecheck: true
#     lint: true

# Factory-wide Definition of Done (I3). The runner runs these gates on every
# non-empty delivery BEFORE it can reach the human review lane; a failing gate
# auto-rejects the delivery back to rework. A repo's own definition_of_done
# overrides this. Shipped gates: tests / typecheck / lint.
definition_of_done:
  enabled: true
  tests: true
  typecheck: true
  lint: true

agents: []
# - id: claude-auth-01
#   display_name: Claude Auth Implementer
#   capabilities: [backend, auth, tests]
#   max_risk: medium
#   allowed_repos: [auth-service]
#   status: active

safety:
  policy_file: ./safety_policy.yaml
  default_idle_loop_mode: create_draft_tickets
  require_clean_worktree_before_start: true
  redact_secrets_in_context: true
  model_may_read_secret_files: false # secrets never enter model context

loops:
  # Factory-wide default delivered-ticket threshold for the idle SCAN loops
  # below. A scan loop SKIPS a repo until that repo has had this many tickets
  # DELIVERED (status 'done') — so a brand-new repo isn't tech-debt/security
  # scanned until it has shipped real work. Each loop can override this with its
  # own 'min_delivered_tickets'. 0 = no gate (scan every in-scope repo).
  default_min_delivered_tickets: 0
  implementation:
    enabled: true
    trigger: manual_or_queue
    max_concurrent_agents: 1
    requires_claim: true
    submit_for_review: true
    claim_ttl_seconds: 900
    # Verifiable delivery post-conditions. When enabled, a delivery missing a
    # required step (branch prefix, test evidence, AC evidence, lint clean) is
    # blocked instead of submitted for review — enforced, not just trusted.
    post_conditions:
      enabled: false
      require_branch_prefix: true
      require_test_evidence: true
      require_ac_evidence: true
      require_lint_clean: true
  # ── Idle SCAN loops ────────────────────────────────────────────────────────
  # OFF by default: each idle tick spends model tokens analysing repos, so a
  # scan loop only runs once you flip 'enabled: true'. Two knobs per loop:
  #   • enabled — turn the loop on for this factory.
  #   • min_delivered_tickets — per-loop delivered-ticket threshold; null means
  #     inherit loops.default_min_delivered_tickets above. A loop skips any repo
  #     under its threshold (recorded as loop_finished/skipped_below_threshold).
  idle_coverage:
    enabled: false # set true to scan coverage on idle ticks
    trigger: when_queue_empty
    # observe_only | create_draft_tickets | create_ready_tickets — idle loops never edit code
    mode: create_draft_tickets
    repos: []
    min_delivered_tickets: null # null = inherit default_min_delivered_tickets
    minimum_gap_threshold: 10
  idle_test_quality:
    enabled: false
    trigger: when_queue_empty
    mode: create_draft_tickets
    repos: []
    min_delivered_tickets: null # e.g. 3 → only scan repos with 3+ delivered tickets
  idle_documentation:
    enabled: false
    trigger: when_queue_empty
    mode: create_draft_tickets
    repos: []
    min_delivered_tickets: null
  idle_dependencies:
    enabled: false
    trigger: when_queue_empty
    mode: create_draft_tickets
    repos: []
    min_delivered_tickets: null
    audit_command: null # e.g. "pnpm outdated --json"; read-only, never installs
  idle_security_hotspot:
    enabled: false # in-source secret/injection/unsafe-API scan; opt in per factory
    trigger: when_queue_empty
    mode: create_draft_tickets
    repos: []
    min_delivered_tickets: null
  idle_type_quality:
    enabled: false # type-debt scan (as casts / non-null ! / @ts-* / skipLibCheck); opt in per factory
    trigger: when_queue_empty
    mode: create_draft_tickets
    repos: []
    min_delivered_tickets: null
  idle_tech_debt:
    enabled: false # refactor-hotspot scan (god-files / churn×size / duplication); opt in per factory
    trigger: when_queue_empty
    mode: create_draft_tickets
    repos: []
    min_delivered_tickets: null
    god_file_lines: 500 # non-test source files over this LOC are flagged as god-files
    churn_size_product_threshold: 5000 # flag when (commit count × LOC) exceeds this
  idle_lore_gap:
    enabled: false # requires a real Memory; emits suggestions, never edits code
    trigger: when_queue_empty
    mode: suggest_lore
    repos: []
    minimum_occurrences: 3
    draft_ratify_ticket: false # also draft a Dispatch ticket to ratify the lore
  # ── Idle MAINTENANCE LANE (audit item A4) ──────────────────────────────────
  # OFF by default. When ON (and GAFFER_MAINTENANCE=1 in the runner), a quiet
  # idle tick runs ONE maintenance loop chosen by a DETERMINISTIC priority +
  # rotation scheduler — NO LLM in the choice — instead of every idle loop or a
  # single fixed scan. Priority: security_hotspot → coverage/test_quality →
  # type_quality/tech_debt → documentation/dependency_hygiene; it rotates so no
  # lane starves and the same lane is not picked on consecutive ticks. The lane
  # only rotates through loops you have enabled above (each loop's own flag is
  # the on/off switch); this block gates the lane itself + the rotation cursor.
  maintenance:
    enabled: false # set true (and GAFFER_MAINTENANCE=1) for the smart prioritised lane
    cursor_path: null # null = <GAFFER_DATA>/maintenance-cursor.json; survives across ticks
  # The self-improving closed loop. OFF BY DEFAULT. When on, an idle tick may
  # promote its OWN drafted improvement tickets to 'ready' so the delivery loop
  # claims them — no human in the promote step. Deliberately hard to fire:
  # strict opt-in (a repo must be named in 'repos'; empty = none), capped per
  # tick, and limited to repos at/below 'max_risk'.
  self_improve:
    enabled: false
    repos: [] # strict opt-in — empty means NO repos are auto-promoted
    max_risk: low # only repos at/below this risk level may be promoted
    max_ready_per_run: 1 # hard cap on auto-promotions per idle tick

# Context-packet token hygiene. Caps keep each per-ticket packet lean and
# pre-filtered to the ticket's stack/area. Token cost per packet is measured and
# reported on the 'context_packet_built' event; set token_budget to flag (never
# silently truncate) packets that exceed your target.
context:
  lore_limit: 8 # max ratified lore records pulled into a packet
  max_skills: 12 # max skills selected after stack filtering
  product_context_limit: 6 # max product-intent lore (decisions/requirements/non-goals) in the productContext section
  token_budget: null # e.g. 4000; soft budget, packets over it are flagged

# GitHub issue ingest: the on-ramp so teammates can file Dispatch work by
# labelling a GitHub issue instead of writing a ticket by hand. Off by default.
# When enabled, 'crew ingest' lists open issues labelled 'label', creates a
# DRAFT Dispatch ticket per issue, then relabels the issue to 'ingested_label'
# so it is not picked up again (idempotent via relabelling). Requires the 'gh'
# CLI authenticated on the host. Only repos with a github.com remote are polled.
ingest:
  github:
    enabled: false
    label: agent-ok # teammates apply this label to opt an issue in
    ingested_label: agent-queued # applied after ingest so it is not re-ingested
    # repos: [] # optional allow-list of repo names; omit/empty = all repos
  # Jira sibling of the GitHub on-ramp; shares the same identity-based dedup
  # (Source: <issue self URL>). Requires the 'jira' CLI authenticated on the host.
  jira:
    enabled: false
    label: agent-ok # teammates apply this label to opt an issue in
    # jql: null # optional JQL override; default scopes to labels = "<label>"
    # repo: null # optional repo name to attach created drafts to

# Hooks are advisory: they may veto a claim or emit events/warnings, but they
# can never bypass safety policy. Disabled by default; opt into built-ins here.
hooks:
  enabled: false
  builtins:
    risk_guard_claim: false
    record_environment: false
    require_evidence_before_review: false
    notify_on_blocked: false
    classify_failure: false
    # Prompts the agent to capture durable lore at after_ticket_done so the normal
    # plan→build→review flow actively builds Memory. On by default once hooks are
    # enabled above.
    capture_lore_reflection: true

logging:
  level: info
  event_log_path: ./.crew/events.jsonl
  redact: true
`;
}

export function defaultSafetyPolicyYaml(): string {
  return `# Crew safety policy.
# Safe-by-default: destructive Git ops denied, secrets denied, dependency
# changes approval-gated. Tighten or loosen per your factory's risk appetite.

git:
  deny_force_push: true
  deny_push_to_protected_branches: true
  deny_delete_branch: true
  deny_tag_mutation: true
  deny_rebase_shared_branch: true
  require_branch_prefix: dispatch/
  protected_branches:
    - main
    - master
    - develop
    - production
    - release/*
    - hotfix/*

filesystem:
  allowed_roots: [] # populated from your repo paths
  deny_write_paths:
    - .git/**
    - .env
    - .env.*
    - "**/secrets/**"
    - "**/credentials/**"
    - "**/*.pem"
    - "**/*.key"
    - "**/id_rsa"
    - "**/id_ed25519"
    - "**/.aws/**"
    - "**/.ssh/**"
  require_approval_write_paths:
    - .github/workflows/**
    - infra/**
    - terraform/**
    - k8s/**
    - Dockerfile
    - docker-compose.yml
    - package.json
    - package-lock.json
    - pnpm-lock.yaml
    - yarn.lock
    - poetry.lock
    - requirements.txt
    - migrations/**

commands:
  deny:
    - "rm -rf /"
    - "rm -rf .git"
    - "chmod -R 777"
    - "chown -R"
    - "git push --force"
    - "git push -f"
    - "git clean -fdx"
    - "git branch -D"
    - "git tag -d"
    - "terraform destroy"
    - "kubectl delete"
    - "docker system prune -a"
  require_approval:
    - "git reset --hard"
    - "git rebase"
    - "npm install"
    - "pnpm install"
    - "yarn install"
    - "pip install"
    - "poetry add"
    - "cargo update"
    - "docker compose down -v"
    - "terraform apply"
    - "kubectl apply"
  allow: []
  allow_from_repo_config: true

secrets:
  redact_in_context: true
  deny_secret_file_reads: true
  high_entropy_redaction: true
`;
}
